import * as vscode from "vscode";

import { Position, PositionDiff } from './../motion/position';
import { Range } from './../motion/range';
import { VimState } from './../mode/modeHandler';
import { ModeName } from './../mode/mode';
import { TextEditor } from './../textEditor';

export module Commenter {
  let delimiterMap= {
      'aap': { 'left': '#' },
      'abc': { 'left': '%' },
      'acedb': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'actionscript': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ada': { 'left': '--', 'leftAlt': '--  ' },
      'ahdl': { 'left': '--' },
      'ahk': { 'left': ';', 'leftAlt': '/*', 'rightAlt': '*/' },
      'amiga': { 'left': ';' },
      'aml': { 'left': '/*' },
      'ampl': { 'left': '#' },
      'apache': { 'left': '#' },
      'apachestyle': { 'left': '#' },
      'applescript': { 'left': '--', 'leftAlt': '(*', 'rightAlt': '*)' },
      'armasm': { 'left': ';' },
      'asciidoc': { 'left': '//' },
      'asm': { 'left': ';', 'leftAlt': '#' },
      'asm68k': { 'left': ';' },
      'asn': { 'left': '--' },
      'asp': { 'left': '%', 'leftAlt': '%*','rightAlt': '*%' },
      'aspvbs': { 'left': "''", 'leftAlt': '<!--', 'rightAlt': '-->' },
      'asterisk': { 'left': ';' },
      'asy': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'atlas': { 'left': 'C', 'right': '$' },
      'autohotkey': { 'left': ';', 'leftAlt': '/*', 'rightAlt': '*/' },
      'autoit': { 'left': ';' },
      'ave': { 'left': "'" },
      'awk': { 'left': '#' },
      'basic': { 'left': "'", 'leftAlt': 'REM ' },
      'bbx': { 'left': '%' },
      'bc': { 'left': '#' },
      'bib': { 'left': '//' },
      'bindzone': { 'left': ';' },
      'blade': { 'left': '{{--', 'right': '--}}' },
      'bst': { 'left': '%' },
      'btm': { 'left': '::' },
      'c': { 'left': '/*','right': '*/', 'leftAlt': '//' },
      'cabal': { 'left': '--' },
      'calibre': { 'left': '//' },
      'caos': { 'left': '*' },
      'catalog': { 'left': '--', 'right': '--' },
      'cf': { 'left': '<!---', 'right': '--->' },
      'cfg': { 'left': '#' },
      'cg': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ch': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'cl': { 'left': '#' },
      'clean': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'clipper': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'clojure': { 'left': ';' },
      'cmake': { 'left': '#' },
      'coffee': { 'left': '#', 'leftAlt': '###', 'rightAlt': '###' },
      'conkyrc': { 'left': '#' },
      'context': { 'left': '%', 'leftAlt': '--' },
      'coq': { 'left': '(*', 'right': '*)' },
      'cpp': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'crontab': { 'left': '#' },
      'cs': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'csp': { 'left': '--' },
      'cterm': { 'left': '*' },
      'cucumber': { 'left': '#' },
      'cuda': { 'left': '/*','right': '*/', 'leftAlt': '//' },
      'cvs': { 'left': 'CVS:' },
      'cython': { 'left': '# ', 'leftAlt': '#' },
      'd': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'dakota': { 'left': '#' },
      'dcl': { 'left': '$!' },
      'debcontrol': { 'left': '#' },
      'debsources': { 'left': '#' },
      'def': { 'left': ';' },
      'desktop': { 'left': '#' },
      'dhcpd': { 'left': '#' },
      'diff': { 'left': '#' },
      'django': { 'left': '<!--','right': '-->', 'leftAlt': '{#', 'rightAlt': '#}' },
      'dns': { 'left': ';' },
      'docbk': { 'left': '<!--', 'right': '-->' },
      'dockerfile': { 'left': '#' },
      'dosbatch': { 'left': 'REM ', 'leftAlt': '::' },
      'dosini': { 'left': ';' },
      'dot': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'dracula': { 'left': ';' },
      'dsl': { 'left': ';' },
      'dtml': { 'left': '<dtml-comment>', 'right': '</dtml-comment>' },
      'dylan': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ebuild': { 'left': '#' },
      'ecd': { 'left': '#' },
      'eclass': { 'left': '#' },
      'eiffel': { 'left': '--' },
      'elf': { 'left': "'" },
      'elixir': { 'left': '#' },
      'elm': { 'left': '--' },
      'elmfilt': { 'left': '#' },
      'ember-script': { 'left': '#' },
      'emblem': { 'left': '/' },
      'erlang': { 'left': '%', 'leftAlt': '%%' },
      'eruby': { 'left': '<%#', 'right': '%>', 'leftAlt': '<!--', 'rightAlt': '-->' },
      'esmtprc': { 'left': '#' },
      'expect': { 'left': '#' },
      'exports': { 'left': '#' },
      'factor': { 'left': '! ', 'leftAlt': '!# ' },
      'fancy': { 'left': '#' },
      'fgl': { 'left': '#' },
      'focexec': { 'left': '-*' },
      'form': { 'left': '*' },
      'fortran': { 'left': '!' },
      'foxpro': { 'left': '*' },
      'fsharp': { 'left': '(*', 'right': '*)', 'leftAlt': '//' },
      'fstab': { 'left': '#' },
      'fvwm': { 'left': '#' },
      'fx': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'gams': { 'left': '*' },
      'gdb': { 'left': '#' },
      'gdmo': { 'left': '--' },
      'geek': { 'left': 'GEEK_COMMENT:' },
      'genshi': { 'left': '<!--','right': '-->', 'leftAlt': '{#', 'rightAlt': '#}' },
      'gentoo-conf-d': { 'left': '#' },
      'gentoo-env-d': { 'left': '#' },
      'gentoo-init-d': { 'left': '#' },
      'gentoo-make-conf': { 'left': '#' },
      'gentoo-package-keywords': { 'left': '#' },
      'gentoo-package-mask': { 'left': '#' },
      'gentoo-package-use': { 'left': '#' },
      'gitcommit': { 'left': '#' },
      'gitconfig': { 'left': ';' },
      'gitrebase': { 'left': '#' },
      'gnuplot': { 'left': '#' },
      'go': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'groovy': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'gsp': { 'left': '<%--', 'right': '--%>', 'leftAlt': '<!--','rightAlt': '-->'},
      'gtkrc': { 'left': '#' },
      'h': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'haml': { 'left': '-#', 'leftAlt': '/' },
      'handlebars': { 'left': '{{!-- ', 'right': ' --}}' },
      'haskell': { 'left': '{-','right': '-}', 'nested': 1, 'leftAlt': '--', 'nestedAlt': 1 },
      'haxe': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'hb': { 'left': '#' },
      'hbs': { 'left': '{{!-- ', 'right': ' --}}' },
      'hercules': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'hive': { 'left': '-- ' },
      'hog': { 'left': '#' },
      'hostsaccess': { 'left': '#' },
      'htmlcheetah': { 'left': '##' },
      'htmldjango': { 'left': '<!--','right': '-->', 'leftAlt': '{#', 'rightAlt': '#}' },
      'htmlos': { 'left': '#', 'right': '/#' },
      'hxml': { 'left': '#' },
      'hyphy': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ia64': { 'left': '#' },
      'icon': { 'left': '#' },
      'idl': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'idlang': { 'left': ';' },
      'idris': { 'leftAlt': '--', 'left': '{-', 'right': '-}' },
      'inform': { 'left': '!' },
      'inittab': { 'left': '#' },
      'ishd': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'iss': { 'left': ';' },
      'ist': { 'left': '%' },
      'jade': { 'left': '//-', 'leftAlt': '//' },
      'java': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'javacc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'javascript': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'javascript.jquery': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'jess': { 'left': ';' },
      'jgraph': { 'left': '(*', 'right': '*)' },
      'jinja': { 'left': '<!--','right': '-->', 'leftAlt': '{#', 'rightAlt': '#}' },
      'jproperties': { 'left': '#' },
      'jsp': { 'left': '<%--', 'right': '--%>' },
      'julia': { 'left': '#' },
      'kix': { 'left': ';' },
      'kscript': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'lace': { 'left': '--' },
      'laravel': { 'left': '{{--', 'right': '--}}' },
      'ldif': { 'left': '#' },
      'less': { 'left': '/*','right': '*/' },
      'lhaskell': { 'left': '>{-','right': '-}', 'leftAlt': '>-- ' },
      'lilo': { 'left': '#' },
      'lilypond': { 'left': '%' },
      'liquid': { 'left': '{% comment %}', 'right': '{% endcomment %}' },
      'lisp': { 'left': ';', 'nested': 1, 'leftAlt': '#|', 'rightAlt': '|#', 'nestedAlt': 1 },
      'llvm': { 'left': ';' },
      'lotos': { 'left': '(*', 'right': '*)' },
      'lout': { 'left': '#' },
      'lpc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'lprolog': { 'left': '%' },
      'lscript': { 'left': "'" },
      'lss': { 'left': '#' },
      'lua': { 'left': '--', 'leftAlt': '--[[', 'rightAlt': ']]' },
      'lynx': { 'left': '#' },
      'lytex': { 'left': '%' },
      'm4': { 'left': 'dnl ' },
      'mail': { 'left': '> ' },
      'mako': { 'left': '##' },
      'man': { 'left': '."' },
      'map': { 'left': '%' },
      'maple': { 'left': '#' },
      'markdown': { 'left': '<!--', 'right': '-->' },
      'masm': { 'left': ';' },
      'mason': { 'left': '<% #', 'right': '%>' },
      'master': { 'left': '$' },
      'matlab': { 'left': '%', 'leftAlt': '%{', 'rightAlt': '%}' },
      'mel': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'mib': { 'left': '--' },
      'mips': { 'left': '#'},
      'mirah': {'left': '#'},
      'mkd': { 'left': '<!---', 'right': '-->' },
      'mma': { 'left': '(*', 'right': '*)' },
      'model': { 'left': '$', 'right': '$' },
      'moduala.': { 'left': '(*', 'right': '*)' },
      'modula2': { 'left': '(*', 'right': '*)' },
      'modula3': { 'left': '(*', 'right': '*)' },
      'monk': { 'left': ';' },
      'mush': { 'left': '#' },
      'mustache': { 'left': '{{!', 'right': '}}' },
      'nagios': { 'left': ';' },
      'named': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'nasm': { 'left': ';' },
      'nastran': { 'left': '$' },
      'natural': { 'left': '/*' },
      'ncf': { 'left': ';' },
      'newlisp': { 'left': ';' },
      'nginx': { 'left': '#' },
      'nimrod': { 'left': '#' },
      'nroff': { 'left': '\"' },
      'nsis': { 'left': '#' },
      'ntp': { 'left': '#' },
      'objc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'objcpp': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'objj': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ocaml': { 'left': '(*', 'right': '*)', 'nested': 1 },
      'occam': { 'left': '--' },
      'octave': { 'left': '%', 'leftAlt': '#' },
      'omlet': { 'left': '(*', 'right': '*)' },
      'omnimark': { 'left': ';' },
      'ooc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'openroad': { 'left': '//' },
      'opl': { 'left': "REM" },
      'ora': { 'left': '#' },
      'ox': { 'left': '//' },
      'paludis-use-conf': { 'left': '#' },
      'pandoc': { 'left': '<!--', 'right': '-->' },
      'pascal': { 'left': '{','right': '}', 'leftAlt': '(*', 'rightAlt': '*)' },
      'patran': { 'left': '$', 'leftAlt': '/*', 'rightAlt': '*/' },
      'pcap': { 'left': '#' },
      'pccts': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'pdf': { 'left': '%' },
      'perl': { 'left': '#' },
      'pfmain': { 'left': '//' },
      'php': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'pic': { 'left': ';' },
      'pike': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'pilrc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'pine': { 'left': '#' },
      'plm': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'plsql': { 'left': '-- ', 'leftAlt': '/*', 'rightAlt': '*/' },
      'po': { 'left': '#' },
      'postscr': { 'left': '%' },
      'pov': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'povini': { 'left': ';' },
      'ppd': { 'left': '%' },
      'ppwiz': { 'left': ';;' },
      'privoxy': { 'left': '#' },
      'processing': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'prolog': { 'left': '%', 'leftAlt': '/*', 'rightAlt': '*/' },
      'ps1': { 'left': '#' },
      'psf': { 'left': '#' },
      'ptcap': { 'left': '#' },
      'pug': { 'left': '//-', 'leftAlt': '//' },
      'puppet': { 'left': '#' },
      'pyrex': { 'left': '# ', 'leftAlt': '#' },
      'python': { 'left': '# ', 'leftAlt': '#' },
      'r': { 'left': '#', 'leftAlt': "#''" },
      'racket': { 'left': ';', 'nested': 1, 'leftAlt': '#|', 'rightAlt': '|#', 'nestedAlt': 1 },
      'radiance': { 'left': '#' },
      'ratpoison': { 'left': '#' },
      'rc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'rebol': { 'left': ';' },
      'registry': { 'left': ';' },
      'remind': { 'left': '#' },
      'resolv': { 'left': '#' },
      'rgb': { 'left': '!' },
      'rib': { 'left': '#' },
      'rmd': { 'left': '#' },
      'robots': { 'left': '#' },
      'rspec': { 'left': '#' },
      'ruby': { 'left': '#', 'leftAlt': '=begin', 'rightAlt': '=end' },
      'rust': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'sa': { 'left': '--' },
      'samba': { 'left': ';', 'leftAlt': '#' },
      'sass': { 'left': '//', 'leftAlt': '/*' },
      'sather': { 'left': '--' },
      'scala': { 'left': '//', 'nested': 1, 'leftAlt': '/*', 'rightAlt': '*/', 'nestedAlt': 1 },
      'scheme': { 'left': ';', 'nested': 1, 'leftAlt': '#|', 'rightAlt': '|#', 'nestedAlt': 1 },
      'scilab': { 'left': '//' },
      'scons': { 'left': '#' },
      'scsh': { 'left': ';' },
      'scss': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/'},
      'sed': { 'left': '#' },
      'sgmldecl': { 'left': '--', 'right': '--' },
      'sgmllnx': { 'left': '<!--', 'right': '-->' },
      'sh': { 'left': '#' },
      'sicad': { 'left': '*' },
      'sile': { 'left': '%' },
      'simula': { 'left': '%', 'leftAlt': '--' },
      'sinda': { 'left': '$' },
      'skill': { 'left': ';' },
      'slang': { 'left': '%' },
      'slice': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'slim': { 'left': '/', 'leftAlt': '/!' },
      'slrnrc': { 'left': '%' },
      'sls': { 'left': '#' },
      'sm': { 'left': '#' },
      'smarty': { 'left': '{*', 'right': '*}' },
      'smil': { 'left': '<!', 'right': '>' },
      'smith': { 'left': ';' },
      'sml': { 'left': '(*', 'right': '*)', 'nested': 1 },
      'snippets': { 'left': '#' },
      'snnsnet': { 'left': '#' },
      'snnspat': { 'left': '#' },
      'snnsres': { 'left': '#' },
      'snobol4': { 'left': '*' },
      'spec': { 'left': '#' },
      'specman': { 'left': '//' },
      'spectre': { 'left': '//', 'leftAlt': '*' },
      'spice': { 'left': '$' },
      'spin': { 'left': "''", 'leftAlt': '{', 'rightAlt': '}' },
      'sql': { 'left': '-- ' },
      'sqlforms': { 'left': '-- ' },
      'sqlj': { 'left': '-- ' },
      'sqr': { 'left': '!' },
      'squid': { 'left': '#' },
      'ss': { 'left': ';', 'leftAlt': '#|', 'rightAlt': '|#' },
      'sshdconfig': { 'left': '#' },
      'st': { 'left': '"' },
      'stan': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'stp': { 'left': '/*','right': '*/', 'leftAlt': '//' },
      'supercollider': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'swift': { 'left': '/*','right': '*/', 'leftAlt': '//' },
      'systemverilog': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'tads': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'tags': { 'left': ';' },
      'tak': { 'left': '$' },
      'tasm': { 'left': ';' },
      'tcl': { 'left': '#' },
      'teak': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'terraform': { 'left': '#', 'leftAlt': '/*', 'rightAlt': '*/'  },
      'tex': { 'left': '%' },
      'texinfo': { 'left': "@c " },
      'texmf': { 'left': '%' },
      'tf': { 'left': ';' },
      'tidy': { 'left': '#' },
      'tli': { 'left': '#' },
      'tmux': { 'left': '#' },
      'toml': { 'left': '#' },
      'trasys': { 'left': "$" },
      'tsalt': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'tsscl': { 'left': '#' },
      'tssgm': { 'left': "comment = '", 'right': "'" },
      'tup': { 'left': '#' },
      'twig': { 'left': '{#', 'right': '#}' },
      'txt2tags': { 'left': '%' },
      'typescript': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'uc': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'uil': { 'left': '!' },
      'upstart': { 'left': '#' },
      'vala': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'vb': { 'left': "'" },
      'velocity': { 'left': "##", 'right': "", 'leftAlt': '#*', 'rightAlt': '*#' },
      'vera': { 'left': '/*','right': '*/', 'leftAlt': '//' },
      'verilog': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'verilog_systemverilog': { 'left': '//', 'leftAlt': '/*', 'rightAlt': '*/' },
      'vgrindefs': { 'left': '#' },
      'vhdl': { 'left': '--' },
      'vimperator': { 'left': '"' },
      'virata': { 'left': '%' },
      'vrml': { 'left': '#' },
      'vsejcl': { 'left': '/*' },
      'webmacro': { 'left': '##' },
      'wget': { 'left': '#' },
      'wikipedia': { 'left': '<!--', 'right': '-->' },
      'winbatch': { 'left': ';' },
      'wml': { 'left': '#' },
      'wvdial': { 'left': ';' },
      'xdefaults': { 'left': '!' },
      'xkb': { 'left': '//' },
      'xmath': { 'left': '#' },
      'xpm2': { 'left': '!' },
      'xquery': { 'left': '(:', 'right': ':)' },
      'yaml': { 'left': '#' },
      'z8a': { 'left': ';' }
  }

  export function toggleLineComments(vimState: VimState, lines: number[], languageId: string) {
    console.log(languageId);

    var delims = delimiterMap[languageId];
    if (!delims) return;

    var leftDelim = delims.left + " ";
    var regex = new RegExp(`[ \t]{1,}(${leftDelim})`);
    for (var index of lines) {
      var line = TextEditor.getLineAt(new Position(index, 0));

      var match = regex.exec(line.text);
      if (match) {
        var matchText = match[0];
        var start = new Position(index, match.index + matchText.length - leftDelim.length);
        var end = new Position(index, match.index + matchText.length);

        vimState.recordedState.transformations.push({
          type: "deleteRange",
          range: new Range(start, end),
        });

        continue;
      }

      var pos = new Position(index, line.firstNonWhitespaceCharacterIndex);
      vimState.recordedState.transformations.push({
        type    : "insertText",
        text    : leftDelim,
        position: pos
      });
    }
  }
}